### ISSUE TITLE
Can you add the configuration.h and Configuration_adv.h so people can customize it?

### ISSUE THREAD

**Issue by gatlace** [haqbany/Bigtreetouch-SKR-Mini-E3V3.0#5]
Firstly, thank you so much for providing/maintaining this firmware. It's the only one I can use that gets my TFT35-E3V3 and my SKR Mini E3V3 working together.

I am printing a new print head, and I would like to edit the Probe offset. I downloaded the source code, but it doesn't have the configuration in it. Can you add the configuration header files so people can customize your firmware?

**Comment by haqbany** [comment]
Hi thank you for your email, Unfortunately this project is in hold now and I have stopped working on it, due to some other personal projects that need my full attention. Best wishes Rashid Sent from my iPhoneOn 18 Feb 2023, at 9:18 PM, Zii Donato ***@***.***> wrote:﻿
Firstly, thank you so much for providing/maintaining this firmware. It's the only one I can use that gets my TFT35-E3V3 and my SKR Mini E3V3 working together.
I am printing a new print head for my BLTouch, and I would like to edit the Probe offset. I downloaded the source code, but it doesn't have the configuration in it. Can you add the configuration header files so people can customize your firmware?
